### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by admapop** [FRSOURCE/cypress-plugin-visual-regression-diff#190]
**Describe the bug**
I'm not sure if I'm missing some setting but it seems to be stuck in a re render loop.

**To Reproduce**

1. Set up plugin as per docs
2. Write a component test
3. cy.get(...).matchImage()
4. Continuously refreshes and generates a load of screenshots

**Expected behavior**
To not have so many screenshots saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/52109936/203840686-93f96ec6-d463-4c58-b85c-6854f717a4cf.png)

**Please complete the following information:**

- OS and version: MacOS 12.3.1
- Browser and version Chrome 107
- Cypress version 11.2.0

**Comment by FRSgit** [comment]
Hey @admapop!

Can you try your code against the newest branch and see if that resolves your issue?

If not, please write what are exact reproduction steps, because the one you've described doesn't lead to the issue reproduction when trying on our [example project.](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/tree/main/example)
You can try to fork this repository and try to get reproduction on the example as well - that way we'll both know what's exactly the issue here.

**Comment by FRSgit** [comment]
Due to no response I'm going to close this issue as stale. If the problems occurs again please file a new issue with reproduction steps provided.
Have a great day!
