### ISSUE TITLE
 Not able to view new screenshot directly in the Cypress UI.

### ISSUE THREAD

**Issue by JavedAubdoolQA** [FRSOURCE/cypress-plugin-visual-regression-diff#75]
Hello FRSOURCE

Firstly I just want to thank you for creating this plugin 

I've followed the installation instructions and nearly got the plugin working however when I click on 'see comparison' in the cypress test runner 
<img width="115" alt="image" src="https://user-images.githubusercontent.com/22030129/180747264-765d6e16-e9ae-43a7-9294-65b08556a4f3.png">
it doesn't allow me to preview old & new screenshot directly in the Cypress UI. 
Also when I open link in a new tab I get the following
 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/22030129/180747886-fcf6cc35-ea91-4494-b75e-e3bbd456d323.png">

Cypress version: v10.2.0

please can you assist and happy to provide more detail if needed

**Comment by FRSgit** [comment]
Hey @JavedAubdoolQA 

Thanks for reaching out, I'll be more than happy to assist!
I'm trying to reproduce it on my private repo, but without any luck. 
Can you provide me with a simple reproduction scenario of this issue? You can use the [example in this repository](https://github.com/FRSOURCE/cypress-plugin-visual-regression-diff/tree/main/example) as a starting point.

**Comment by FRSgit** [comment]
Hey @JavedAubdoolQA - have you got any updates about this issue?
I've tried to reproduce it once again, but without any luck.

Regarding opening link in the new tab: the screenshot comparison is being opened in a modal, it's not a separate page. So opening in a new tab is not supposed to be working. Unfortunately Cypress does not make it easy to customize anchor tags in the test UI - so I think no further action can be done here (I'm open if anyone find a solution though!) 😞

Regarding the original question - as I'm not able to reproduce for 20 days now I'm marking this issue as "stale". If nothing happens in this thread for next week I'll need to close it

**Comment by Pablo-Quiroga-Globant** [comment]
Hello there! I've seen a similar behavior, but using [cypress-mochawesome-reports](https://www.npmjs.com/package/cypress-mochawesome-reporter) plugin. I can see the diff on the Cypress UI, but when I run the tests on headless mode (the default on the CI) the images are not being added to the report. It creates a set of empty folders (where the image should be).

What I'm expecting to see on the report is the original screenshot in case there's no diff. If there is any diff, I expect to see the original screenshot, the diff and the actual.

I'm using cypress-mochawesome-reports default config, and visual regression plugin defaults. The issue becomes more evident when I turn on `embeddedScreenshots` on for the reporter: 

```  
reporter: 'cypress-mochawesome-reporter',
reporterOptions: {
   embeddedScreenshots: true,
},
```

I'm getting the following error: 

```
Start generate report process
Read and merge jsons from "{root_path}/cypress/reports/html/.jsons"
Enhance report
An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:


Error: ENOENT: no such file or directory, open '{root_path}/cypress/screenshots{root_path}/cypress/integration/__image_snapshots__/Error page should validate there are no visual changes #0.actual.png'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at convertImageToBase64 ({root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:111:52)
    at {root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:104:11
    at Array.map (<anonymous>)
    at createScreenshotsContextList ({root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:100:22)
    at attachScreenshotsToTestContext ({root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:76:9)
    at {root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:34:24
    at Array.forEach (<anonymous>)
    at {root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:32:19
    at Array.forEach (<anonymous>)
    at attachScreenshotsToSuiteTestsContext ({root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:31:12)
    at {root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:16:7
    at Array.forEach (<anonymous>)
    at enhanceReport ({root_path}/node_modules/cypress-mochawesome-reporter/lib/enhanceReport.js:6:18)
    at mergeAndCreate ({root_path}/node_modules/cypress-mochawesome-reporter/lib/generateReport.js:19:3)
    at async Promise.all (index 0)
    at async generateReport ({root_path}/node_modules/cypress-mochawesome-reporter/lib/generateReport.js:62:22)
    at async afterRunHook ({root_path}/node_modules/cypress-mochawesome-reporter/lib/index.js:35:3)
    at async Object.handler ({root_path}/node_modules/cypress-mochawesome-reporter/plugin.js:9:5)
```

This is what I see when I disable embeddedScreenshots:

![Screenshot from 2022-08-25 02-48-39](https://user-images.githubusercontent.com/42038861/186585052-3039f953-5bbf-4200-bb93-8d3e2f7e881c.png)

The url of the file is pointing to `file:///{root_path}/cypress/reports/html/screenshots{root_path}/cypress/integration/__image_snapshots__/Error%20page%20should%20validate%20there%20are%20no%20visual%20changes%20#0.actual.png`

Note: `{root_path}` is the full path to the project folder. I'm using linux.

I believe that the issue is related to the path of the image being sent to the test context.

Is this enough detail for a follow up? 

Thank you!

**Comment by FRSgit** [comment]
Hey @Pablo-Quiroga-Globant 👋 

Thanks for the detailed response, it's great!
This thread is about @JavedAubdoolQA not being able to see the screenshot when using "See comparison" button (which comes from this package) while your comment seems to be focusing on the case when the package is used together with some reporting plugin. Could you please open new issue for your scenario and fill out the bug template? 🙏

**Comment by FRSgit** [comment]
Regarding the original info - @JavedAubdoolQA due to lack of response I need to close this issue. Please open up a new issue if you believe that issue still exists and have an example!
And once again - thanks for reaching out 🎉 

@Pablo-Quiroga-Globant please open up a new issue ticket about your scenario, cheers!
